export { default as ColorsPage } from './ColorsPage.vue'
export { default as HomePage } from './HomePage.vue'
export { default as IconsPage } from './IconsPage.vue'
export { default as LogosPage } from './LogosPage.vue'
export { default as SpacingPage } from './SpacingPage.vue'
export { default as SurfacesPage } from './SurfacesPage.vue'
export { default as ThemeComparison } from './ThemeComparison.vue'
export { default as TypographyPage } from './TypographyPage.vue'
