name: 'Quality Checks'
description: 'Run lint, type-check and validation for any package'

inputs:
  package-filter:
    description: 'Turborepo filter for the package to check'
    required: true
  include-dependencies:
    description: 'Include dependencies in checks'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 🔍 Lint code
      shell: bash
      run: |
        if [ "${{ inputs.include-dependencies }}" = "true" ]; then
          turbo lint --filter=...${{ inputs.package-filter }}
        else
          turbo lint --filter=${{ inputs.package-filter }}
        fi

    - name: 🔍 Type check
      shell: bash
      run: |
        if [ "${{ inputs.include-dependencies }}" = "true" ]; then
          turbo type-check --filter=...${{ inputs.package-filter }}
        else
          turbo type-check --filter=${{ inputs.package-filter }}
        fi

    - name: 🎨 Validate design system tokens (if applicable)
      shell: bash
      run: |
        # Check if validate:design-system task exists for this package
        if turbo run validate:design-system --filter=${{ inputs.package-filter }} --dry-run 2>/dev/null; then
          if [ "${{ inputs.include-dependencies }}" = "true" ]; then
            turbo validate:design-system --filter=...${{ inputs.package-filter }}
          else
            turbo validate:design-system --filter=${{ inputs.package-filter }}
          fi
        else
          echo "✅ No design system validation needed for this package"
        fi

    - name: 🧪 Run tests
      shell: bash
      run: |
        # Check if test task exists for this package
        if turbo run test --filter=${{ inputs.package-filter }} --dry-run 2>/dev/null; then
          if [ "${{ inputs.include-dependencies }}" = "true" ]; then
            turbo test --filter=...${{ inputs.package-filter }}
          else
            turbo test --filter=${{ inputs.package-filter }}
          fi
        else
          echo "✅ No tests configured for this package"
        fi